### ISSUE TITLE
V1.2.0 Tag assigned to v1.4.0 release

### ISSUE THREAD

**Issue by mcarvin8** [renatoliveira/apex-test-list#30]
It looks like the v1.4.0 Release is assigned to the v1.2.0 tag. 

![image](https://github.com/user-attachments/assets/a23b376b-78ae-45c7-8f6f-c2fb92cb995c)

Release Please goes based on Tags since the tag is assigned to the commit. And a release can only be created after a tag is made. 

I think you'll need to manually re-create this tag and GitHub release before you have Release Please create new PRs.

Or at least manually create the v1.4.0 tag on the same commit.

**Comment by renatoliveira** [comment]
The tag already exists on the remote, so I just updated the tag on the release. Hope that's alright now. Could you verify?

**Comment by mcarvin8** [comment]
Yea just confirmed the v1.4.0 tag is on the same commit as the 1.2.0 tag. 

I'm curious how'll Release Please will handle this when you release next, but I'm fine with closing until then.

**Comment by mcarvin8** [comment]
The one thing I'm concerned is that the Release Please workflow still only identifies the 1.2.0 tag/release, not the 1.4.0. 

![image](https://github.com/user-attachments/assets/aa73e096-c307-41e2-890e-e41ebebb5a8d)

When I check my plugins, each Release Please job will list all previous releases. 

So I'm still wondering if having that 1.2.0 tag will confuse Release Please during your next releases.

**Comment by renatoliveira** [comment]
Where do you see that? I just pushed the v1.4.0 tag again to the remote repository. Maybe it works fine if I just remove the other tags? 🤔

**Comment by mcarvin8** [comment]
https://github.com/renatoliveira/apex-test-list/actions/runs/10972370651/job/30468561413

Here's the last job log for your Release workflow. If you expand the "Release Please" job, you'll still the log where it goes through your repo history looking for commits to trigger a release.

Part of this git history is finding existing releases.

**Comment by renatoliveira** [comment]
Gotcha! Maybe it starts working just fine if we bump the major version (still working on the test suite parsing).
